# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Pirates Radio-T"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"
description = "Radio-T Theme"
homepage = "https://radio-t.com"
tags = ["website"]
features = ["posts", "shortcodes"]
min_version = 0.25

[author]
  name = "Umputun, Bobuk, Ksenks, Gray, Tema"
  homepage = "https://radio-t.com"
